# Site settings
title: Leanne Young
description: Welcome to the fabulous website of Leanne Young! Here you'll get to learn all about her & the cool things she's been up to.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://leanne-young.github.io/"

# User settings
username: Leanne Young
user_description: Hello! I am a Computer Science & Biology student at McGill University, passionate about brain related things and bridging the gap between the life sciences & the physical sciences. My main interests are in neuroscience, particularly learning & memory, plasticity, and brain-computer interfaces. My other general interests include AI, evolution, robotics, and data science, and I would love to contribute to our growing knowledge base in those fields through research! When I'm not nerding out about science, you'll find me heavily involved as a leader in the tech community, or letting my creative side shine through photography and creating and sharing music with others.
user_title: BSc. Student at McGill University
email: leanneyoung.official@gmail.com
twitter_username: lorem_ipsum
github_username:  https://github.com/leanne-young
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
